# Generated by Django 4.0.3 on 2022-04-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_api', '0002_alter_snack_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='image',
        ),
    ]
