# Generated by Django 4.0.3 on 2022-04-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_api', '0002_snack_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='des',
        ),
    ]
