# Generated by Django 4.0.3 on 2022-04-16 17:29

from django.db import migrations, models
import snacks_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_api', '0003_remove_snack_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=snacks_api.models.nameFile),
        ),
    ]
