# Generated by Django 4.0.3 on 2022-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_api', '0005_alter_snack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
