# Generated by Django 4.0.3 on 2022-04-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks_api', '0002_alter_snack_description'),
        ('snacks_api', '0007_alter_snack_image'),
    ]

    operations = [
    ]
